name: FastAPI CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_aiogram:
    runs-on: ubuntu-latest
    needs: django_ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy FastAPI
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            git pull
